name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build and package
        run: pnpm package

      - name: Cleanup artifacts for windows
        if: matrix.os == 'windows-latest'
        run: npx rimraf "release/build/!(*.exe)"

      - name: Cleanup artifacts for macos
        if: matrix.os == 'macos-latest'
        run: npx rimraf "release/build/!(*.dmg)"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: release/build

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "release/build/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
